### ISSUE TITLE
not work under macOS

### ISSUE THREAD

**Issue by libratiger** [jackwish/bazel#1]
I install the `bazel`with `brew`, and then install the plugin under `.oh-my-zsh/custom/plugins/bazel`. but it does not work. I also source the zsh.

the bazel version is `0.28.1-homebrew`

**Comment by libratiger** [comment]
i just put the following, it works
```
fpath[1,0]=~/.zsh/completion/
mkdir -p ~/.zsh/completion/
cp scripts/zsh_completion/_bazel ~/.zsh/completion
```

**Comment by jackwish** [comment]
> i just put the following, it works
> 
> ```
> fpath[1,0]=~/.zsh/completion/
> mkdir -p ~/.zsh/completion/
> cp scripts/zsh_completion/_bazel ~/.zsh/completion
> ```

Hi @libratiger , thank you for reporting this issue. Mostly the code segment you listed is not needed, because it should have been handled by oh-my-zsh.

Did you put the `bazel` in oh-my-zsh plugin list? 

```
plugins=(
  ...
  bazel
  ...
)
```

**Comment by libratiger** [comment]
Yes ,  i put the ```bazel``` in the plugin list

**Comment by jackwish** [comment]
I have checked on macOS 10.14.5 with tensorflow repo, the plugin looks good...
Did you remember that if there were `~/.zcompdump*` files on your machine, and removed it?

**Comment by libratiger** [comment]
there is no ```~/.zcompdump*```

**Comment by jackwish** [comment]
> there is no `~/.zcompdump*`

Ok, thank you... I will re-check if I had a clean Mac env someday... Thank you.
